package com.nrojiani.drone.scheduler

import com.nrojiani.drone.model.delivery.DroneDelivery
import com.nrojiani.drone.model.order.PendingDeliveryOrder

/**
 * Wrapper class that simply holds the result of a single scheduling operation.
 * @param scheduled A list of [DroneDelivery] generated by scheduling a list of [PendingDeliveryOrder].
 * @param unscheduled The orders that could not be scheduled. Possibly empty.
 */
internal data class SchedulingResult(
    val scheduled: List<DroneDelivery>,
    val unscheduled: List<PendingDeliveryOrder>
)